package Assignment2;

public enum TokenCode {
	  IDENTIFIER, NUMBER, INCDECOP, RELOP, MULOP, ADDOP,
	  ASSIGNOP,
	  CLASS, STATIC, VOID, IF, ELSE, FOR, RETURN, BREAK, CONTINUE, 
	  LBRACE, RBRACE, LBRACKET, RBRACKET, LPAREN, RPAREN,
	  SEMICOLON, COMMA, NOT, INT, REAL,
	  EOF, ERR_ILL_CHAR, ERR_LONG_ID

}
